import Head from 'next/head'
import Link from 'next/link';
import { useContext } from 'react';

import styles from '~/styles/Home.module.css'
import AuthContext from '~/contexts/AuthContext'

export default function Index() {

    const user = useContext(AuthContext);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav>
                <Link href="/"><a>Index</a></Link>
                <Link href="home"><a>Home</a></Link>
            </nav>
            <p>Logged in user: {user?.username}</p>
        </div>
    )
}
