import Head from 'next/head'
import { useContext } from 'react'

import styles from '../styles/Home.module.css'
import AuthContext from './contexts/AuthContext'

export default function Home() {

  const user = useContext(AuthContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{user.username}</p>
    </div>
  )
}
